--game.Players.PlayerAdded:Connect(function(plr)
--	if plr.AccountAge <= 12 then
--		plr:Kick("Your account is not old enough to play this game. This is to prevent hackers from making new accounts, sorry!")
--	end
--end)